### ISSUE TITLE
[Android] App crashes

### ISSUE THREAD

**Issue by dominicrico** [oney/RCTWebRTCDemo#62]
Hey,

trying to use the code from the example, but the App crashes while i'm trying to connect to room.

LogCat tells me this:

```
03-14 15:01:06.120 28462-28650/com.vx.rat E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -22
03-14 15:01:06.151 28462-28633/com.vx.rat E/GLConsumer: [SurfaceTexture-1-28462-0] syncForReleaseLocked: error dup'ing native fence fd: 0x3000
03-14 15:01:06.158 28462-28633/com.vx.rat E/AndroidRuntime: FATAL EXCEPTION: Camera SurfaceTextureHelper
    Process: com.vx.rat, PID: 28462
    java.lang.RuntimeException: Error during updateTexImage (see logcat for details)
        at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
        at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:240)
        at org.webrtc.SurfaceTextureHelper.updateTexImage(SurfaceTextureHelper.java:244)
        at org.webrtc.SurfaceTextureHelper.tryDeliverTextureFrame(SurfaceTextureHelper.java:258)
        at org.webrtc.SurfaceTextureHelper.access$500(SurfaceTextureHelper.java:36)
        at org.webrtc.SurfaceTextureHelper$3.onFrameAvailable(SurfaceTextureHelper.java:132)
        at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:203)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

My device is a Samsung Galaxy S8 with the latest Android Updates.

Thanks for your help!

**Comment by dominicrico** [comment]
Sometimes I get this error:

```
03-14 15:06:54.911 29813-30331/com.vx.rat E/Fence: merge: sync_merge("SurfaceTexture-1-29813-0:2", -1, 1023) returned an error: Too many open files (-24)
03-14 15:06:54.938 29813-29843/com.vx.rat E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -22
03-14 15:06:54.939 29813-29843/com.vx.rat W/OpenGLRenderer: swapBuffers encountered EGL error 12299 on 0xdb9a38f8, halting rendering...
03-14 15:06:54.965 29813-29813/com.vx.rat E/ViewRootImpl@1fc6456[MainActivity]: ViewRootImpl #2 Surface is not valid.
03-14 15:06:55.009 29813-29824/com.vx.rat I/art: Background partial concurrent mark sweep GC freed 150126(6MB) AllocSpace objects, 0(0B) LOS objects, 39% free, 24MB/40MB, paused 11.078ms total 144.691ms
03-14 15:06:55.119 29813-30117/com.vx.rat E/art: ashmem_create_region failed for 'indirect ref table': Too many open files
03-14 15:06:55.119 29813-30117/com.vx.rat W/art: Throwing OutOfMemoryError "Could not allocate JNI Env"
03-14 15:06:55.122 29813-30117/com.vx.rat E/unknown:ReactNative: Exception in native call
  java.lang.RuntimeException: Could not invoke WebSocketModule.connect
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:385)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
    at android.os.Looper.loop(Looper.java:154)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
    at java.lang.Thread.run(Thread.java:762)
 Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Method.invoke(Native Method)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162) 
    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
    at android.os.Handler.handleCallback(Handler.java:751) 
    at android.os.Handler.dispatchMessage(Handler.java:95) 
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
    at android.os.Looper.loop(Looper.java:154) 
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194) 
    at java.lang.Thread.run(Thread.java:762) 
 Caused by: java.lang.OutOfMemoryError: Could not allocate JNI Env
    at java.lang.Thread.nativeCreate(Native Method)
    at java.lang.Thread.start(Thread.java:731)
    at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:941)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1359)
    at okhttp3.Dispatcher.enqueue(Dispatcher.java:129)
    at okhttp3.RealCall.enqueue(RealCall.java:82)
    at okhttp3.internal.ws.RealWebSocket.connect(RealWebSocket.java:180)
    at okhttp3.OkHttpClient.newWebSocket(OkHttpClient.java:415)
    at com.facebook.react.modules.websocket.WebSocketModule.connect(WebSocketModule.java:140)
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374) 
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162) 
    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
    at android.os.Handler.handleCallback(Handler.java:751) 
    at android.os.Handler.dispatchMessage(Handler.java:95) 
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
    at android.os.Looper.loop(Looper.java:154) 
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194) 
    at java.lang.Thread.run(Thread.java:762) 
```

**Comment by umamahacse** [comment]
Hi,
Is there any update regrading the above mentioned issue.
