### ISSUE TITLE
App crashing in android

### ISSUE THREAD

**Issue by ghost** [oney/RCTWebRTCDemo#77]
Hi ,
I tried to run the code but app is continuously crashing in android : My logcat 

2019-01-18 14:28:58.048 751-807/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
2019-01-18 14:28:58.055 2003-3423/? E/ActivityTrigger: activityStartTrigger: not whiteListedcom.rctwebrtcdemo/com.rctwebrtcdemo.MainActivity/1
2019-01-18 14:28:58.057 2003-3423/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.rctwebrtcdemo/com.rctwebrtcdemo.MainActivity/1
2019-01-18 14:28:58.062 2003-3423/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.rctwebrtcdemo/com.rctwebrtcdemo.MainActivity/1
2019-01-18 14:28:58.595 8029-8066/com.rctwebrtcdemo E/unknown:React: Exception in native call
    java.lang.RuntimeException: Error calling AppRegistry.runApplication
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
        at android.os.Looper.loop(Looper.java:176)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.facebook.jni.CppException: Could not get BatchedBridge, make sure your bundle is packaged correctly
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:794) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
        at android.os.Looper.loop(Looper.java:176) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208) 
        at java.lang.Thread.run(Thread.java:764) 
2019-01-18 14:28:58.654 8029-8029/com.rctwebrtcdemo E/WindowManager: BadTokenException or InvalidDisplayException, clean up.
2019-01-18 14:28:58.657 8029-8029/com.rctwebrtcdemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.rctwebrtcdemo, PID: 8029
    android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@d48bbfd -- permission denied for window type 2003
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:820)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)

**Comment by pieter888** [comment]
Did you find out what caused this issue?
